// Code generated by protoc-gen-go. DO NOT EDIT.
// source: managementpb/ia/receivers.proto

package iav1beta1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("managementpb/ia/receivers.proto", fileDescriptor_aed4d28027f7f0c9)
}

var fileDescriptor_aed4d28027f7f0c9 = []byte{
	// 89 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0xcf, 0x4d, 0xcc, 0x4b,
	0x4c, 0x4f, 0xcd, 0x4d, 0xcd, 0x2b, 0x29, 0x48, 0xd2, 0xcf, 0x4c, 0xd4, 0x2f, 0x4a, 0x4d, 0x4e,
	0xcd, 0x2c, 0x4b, 0x2d, 0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0xca, 0x4c, 0xd4,
	0x2b, 0x33, 0x4c, 0x4a, 0x2d, 0x49, 0x34, 0x34, 0xe2, 0xe6, 0xe2, 0x0c, 0x82, 0x49, 0x3b, 0x71,
	0x47, 0x71, 0x66, 0x26, 0x42, 0x65, 0x92, 0xd8, 0xc0, 0x8a, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x77, 0x64, 0x8f, 0xed, 0x4f, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ReceiversClient is the client API for Receivers service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReceiversClient interface {
}

type receiversClient struct {
	cc grpc.ClientConnInterface
}

func NewReceiversClient(cc grpc.ClientConnInterface) ReceiversClient {
	return &receiversClient{cc}
}

// ReceiversServer is the server API for Receivers service.
type ReceiversServer interface {
}

// UnimplementedReceiversServer can be embedded to have forward compatible implementations.
type UnimplementedReceiversServer struct {
}

func RegisterReceiversServer(s *grpc.Server, srv ReceiversServer) {
	s.RegisterService(&_Receivers_serviceDesc, srv)
}

var _Receivers_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ia.v1beta1.Receivers",
	HandlerType: (*ReceiversServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "managementpb/ia/receivers.proto",
}
