// Code generated by protoc-gen-go. DO NOT EDIT.
// source: managementpb/ia/rules.proto

package iav1beta1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	_ "github.com/mwitkow/go-proto-validators"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ParamUnit Integrated Alerting rule parameter unit.
type ParamUnit int32

const (
	ParamUnit_PARAM_UNIT_INVALID ParamUnit = 0
	ParamUnit_PERCENTAGE         ParamUnit = 1
)

var ParamUnit_name = map[int32]string{
	0: "PARAM_UNIT_INVALID",
	1: "PERCENTAGE",
}

var ParamUnit_value = map[string]int32{
	"PARAM_UNIT_INVALID": 0,
	"PERCENTAGE":         1,
}

func (x ParamUnit) String() string {
	return proto.EnumName(ParamUnit_name, int32(x))
}

func (ParamUnit) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f77c2da78f7912f5, []int{0}
}

// ParamType Integrated Alerting rule parameter type.
type ParamType int32

const (
	ParamType_PARAM_TYPE_INVALID ParamType = 0
	ParamType_FLOAT              ParamType = 1
)

var ParamType_name = map[int32]string{
	0: "PARAM_TYPE_INVALID",
	1: "FLOAT",
}

var ParamType_value = map[string]int32{
	"PARAM_TYPE_INVALID": 0,
	"FLOAT":              1,
}

func (x ParamType) String() string {
	return proto.EnumName(ParamType_name, int32(x))
}

func (ParamType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f77c2da78f7912f5, []int{1}
}

type ListAlertingRulesRequest struct {
	// If true, Integrated Alerting rule files will be re-read from disk.
	Reload               bool     `protobuf:"varint,1,opt,name=reload,proto3" json:"reload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAlertingRulesRequest) Reset()         { *m = ListAlertingRulesRequest{} }
func (m *ListAlertingRulesRequest) String() string { return proto.CompactTextString(m) }
func (*ListAlertingRulesRequest) ProtoMessage()    {}
func (*ListAlertingRulesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f77c2da78f7912f5, []int{0}
}

func (m *ListAlertingRulesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAlertingRulesRequest.Unmarshal(m, b)
}
func (m *ListAlertingRulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAlertingRulesRequest.Marshal(b, m, deterministic)
}
func (m *ListAlertingRulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAlertingRulesRequest.Merge(m, src)
}
func (m *ListAlertingRulesRequest) XXX_Size() int {
	return xxx_messageInfo_ListAlertingRulesRequest.Size(m)
}
func (m *ListAlertingRulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAlertingRulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAlertingRulesRequest proto.InternalMessageInfo

func (m *ListAlertingRulesRequest) GetReload() bool {
	if m != nil {
		return m.Reload
	}
	return false
}

type ListAlertingRulesResponse struct {
	// Integrated Alerting rules.
	Rules                []*ListAlertingRulesResponse_Rule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *ListAlertingRulesResponse) Reset()         { *m = ListAlertingRulesResponse{} }
func (m *ListAlertingRulesResponse) String() string { return proto.CompactTextString(m) }
func (*ListAlertingRulesResponse) ProtoMessage()    {}
func (*ListAlertingRulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f77c2da78f7912f5, []int{1}
}

func (m *ListAlertingRulesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAlertingRulesResponse.Unmarshal(m, b)
}
func (m *ListAlertingRulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAlertingRulesResponse.Marshal(b, m, deterministic)
}
func (m *ListAlertingRulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAlertingRulesResponse.Merge(m, src)
}
func (m *ListAlertingRulesResponse) XXX_Size() int {
	return xxx_messageInfo_ListAlertingRulesResponse.Size(m)
}
func (m *ListAlertingRulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAlertingRulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAlertingRulesResponse proto.InternalMessageInfo

func (m *ListAlertingRulesResponse) GetRules() []*ListAlertingRulesResponse_Rule {
	if m != nil {
		return m.Rules
	}
	return nil
}

// Param repsesents a single Integrated Alerting rule parameter.
type ListAlertingRulesResponse_Param struct {
	// Parameter name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Parameter description.
	Help string `protobuf:"bytes,2,opt,name=help,proto3" json:"help,omitempty"`
	// Parameter unit.
	Unit ParamUnit `protobuf:"varint,3,opt,name=unit,proto3,enum=ia.v1beta1.ParamUnit" json:"unit,omitempty"`
	// Parameter type.
	Type ParamType `protobuf:"varint,4,opt,name=type,proto3,enum=ia.v1beta1.ParamType" json:"type,omitempty"`
	// Parameter minimal value (float).
	MinValue float32 `protobuf:"fixed32,5,opt,name=min_value,json=minValue,proto3" json:"min_value,omitempty"`
	// Parameter maximum value (float).
	MaxValue float32 `protobuf:"fixed32,6,opt,name=max_value,json=maxValue,proto3" json:"max_value,omitempty"`
	// Parameter set value (float).
	DefaultValue float32 `protobuf:"fixed32,7,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	// Parameter set value (float).
	Value                float32  `protobuf:"fixed32,8,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAlertingRulesResponse_Param) Reset()         { *m = ListAlertingRulesResponse_Param{} }
func (m *ListAlertingRulesResponse_Param) String() string { return proto.CompactTextString(m) }
func (*ListAlertingRulesResponse_Param) ProtoMessage()    {}
func (*ListAlertingRulesResponse_Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_f77c2da78f7912f5, []int{1, 0}
}

func (m *ListAlertingRulesResponse_Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAlertingRulesResponse_Param.Unmarshal(m, b)
}
func (m *ListAlertingRulesResponse_Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAlertingRulesResponse_Param.Marshal(b, m, deterministic)
}
func (m *ListAlertingRulesResponse_Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAlertingRulesResponse_Param.Merge(m, src)
}
func (m *ListAlertingRulesResponse_Param) XXX_Size() int {
	return xxx_messageInfo_ListAlertingRulesResponse_Param.Size(m)
}
func (m *ListAlertingRulesResponse_Param) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAlertingRulesResponse_Param.DiscardUnknown(m)
}

var xxx_messageInfo_ListAlertingRulesResponse_Param proto.InternalMessageInfo

func (m *ListAlertingRulesResponse_Param) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListAlertingRulesResponse_Param) GetHelp() string {
	if m != nil {
		return m.Help
	}
	return ""
}

func (m *ListAlertingRulesResponse_Param) GetUnit() ParamUnit {
	if m != nil {
		return m.Unit
	}
	return ParamUnit_PARAM_UNIT_INVALID
}

func (m *ListAlertingRulesResponse_Param) GetType() ParamType {
	if m != nil {
		return m.Type
	}
	return ParamType_PARAM_TYPE_INVALID
}

func (m *ListAlertingRulesResponse_Param) GetMinValue() float32 {
	if m != nil {
		return m.MinValue
	}
	return 0
}

func (m *ListAlertingRulesResponse_Param) GetMaxValue() float32 {
	if m != nil {
		return m.MaxValue
	}
	return 0
}

func (m *ListAlertingRulesResponse_Param) GetDefaultValue() float32 {
	if m != nil {
		return m.DefaultValue
	}
	return 0
}

func (m *ListAlertingRulesResponse_Param) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

// Rule represents Integrated Alerting rule.
type ListAlertingRulesResponse_Rule struct {
	// Rule name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Rules status: enabled or disabled.
	Enabled bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Rule description.
	Help string `protobuf:"bytes,3,opt,name=help,proto3" json:"help,omitempty"`
	// Rule parameters.
	Params []*ListAlertingRulesResponse_Param `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty"`
	// Rule default duration.
	DefaultFor *duration.Duration `protobuf:"bytes,5,opt,name=default_for,json=defaultFor,proto3" json:"default_for,omitempty"`
	// Rule set duration.
	For                  *duration.Duration `protobuf:"bytes,6,opt,name=for,proto3" json:"for,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListAlertingRulesResponse_Rule) Reset()         { *m = ListAlertingRulesResponse_Rule{} }
func (m *ListAlertingRulesResponse_Rule) String() string { return proto.CompactTextString(m) }
func (*ListAlertingRulesResponse_Rule) ProtoMessage()    {}
func (*ListAlertingRulesResponse_Rule) Descriptor() ([]byte, []int) {
	return fileDescriptor_f77c2da78f7912f5, []int{1, 1}
}

func (m *ListAlertingRulesResponse_Rule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAlertingRulesResponse_Rule.Unmarshal(m, b)
}
func (m *ListAlertingRulesResponse_Rule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAlertingRulesResponse_Rule.Marshal(b, m, deterministic)
}
func (m *ListAlertingRulesResponse_Rule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAlertingRulesResponse_Rule.Merge(m, src)
}
func (m *ListAlertingRulesResponse_Rule) XXX_Size() int {
	return xxx_messageInfo_ListAlertingRulesResponse_Rule.Size(m)
}
func (m *ListAlertingRulesResponse_Rule) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAlertingRulesResponse_Rule.DiscardUnknown(m)
}

var xxx_messageInfo_ListAlertingRulesResponse_Rule proto.InternalMessageInfo

func (m *ListAlertingRulesResponse_Rule) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ListAlertingRulesResponse_Rule) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *ListAlertingRulesResponse_Rule) GetHelp() string {
	if m != nil {
		return m.Help
	}
	return ""
}

func (m *ListAlertingRulesResponse_Rule) GetParams() []*ListAlertingRulesResponse_Param {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *ListAlertingRulesResponse_Rule) GetDefaultFor() *duration.Duration {
	if m != nil {
		return m.DefaultFor
	}
	return nil
}

func (m *ListAlertingRulesResponse_Rule) GetFor() *duration.Duration {
	if m != nil {
		return m.For
	}
	return nil
}

type ChangeAlertingRulesRequest struct {
	// Rule name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Sets new rule status: enabled or disabled. Must always be sent.
	Enabled bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Parameters to change. Missing parameters will not be changed.
	Params []*ChangeAlertingRulesRequest_Param `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty"`
	// Rule set duration.
	For *duration.Duration `protobuf:"bytes,4,opt,name=for,proto3" json:"for,omitempty"`
	// Remove set duration (reset to default).
	RemoveFor            bool     `protobuf:"varint,5,opt,name=remove_for,json=removeFor,proto3" json:"remove_for,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeAlertingRulesRequest) Reset()         { *m = ChangeAlertingRulesRequest{} }
func (m *ChangeAlertingRulesRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeAlertingRulesRequest) ProtoMessage()    {}
func (*ChangeAlertingRulesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f77c2da78f7912f5, []int{2}
}

func (m *ChangeAlertingRulesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeAlertingRulesRequest.Unmarshal(m, b)
}
func (m *ChangeAlertingRulesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeAlertingRulesRequest.Marshal(b, m, deterministic)
}
func (m *ChangeAlertingRulesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeAlertingRulesRequest.Merge(m, src)
}
func (m *ChangeAlertingRulesRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeAlertingRulesRequest.Size(m)
}
func (m *ChangeAlertingRulesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeAlertingRulesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeAlertingRulesRequest proto.InternalMessageInfo

func (m *ChangeAlertingRulesRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChangeAlertingRulesRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *ChangeAlertingRulesRequest) GetParams() []*ChangeAlertingRulesRequest_Param {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *ChangeAlertingRulesRequest) GetFor() *duration.Duration {
	if m != nil {
		return m.For
	}
	return nil
}

func (m *ChangeAlertingRulesRequest) GetRemoveFor() bool {
	if m != nil {
		return m.RemoveFor
	}
	return false
}

// Param repsesents a single Integrated Alerting rule parameter change.
type ChangeAlertingRulesRequest_Param struct {
	// Parameter name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Parameter set value (float).
	Value float32 `protobuf:"fixed32,2,opt,name=value,proto3" json:"value,omitempty"`
	// Remove set value (reset to default).
	RemoveValue          bool     `protobuf:"varint,3,opt,name=remove_value,json=removeValue,proto3" json:"remove_value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeAlertingRulesRequest_Param) Reset()         { *m = ChangeAlertingRulesRequest_Param{} }
func (m *ChangeAlertingRulesRequest_Param) String() string { return proto.CompactTextString(m) }
func (*ChangeAlertingRulesRequest_Param) ProtoMessage()    {}
func (*ChangeAlertingRulesRequest_Param) Descriptor() ([]byte, []int) {
	return fileDescriptor_f77c2da78f7912f5, []int{2, 0}
}

func (m *ChangeAlertingRulesRequest_Param) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeAlertingRulesRequest_Param.Unmarshal(m, b)
}
func (m *ChangeAlertingRulesRequest_Param) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeAlertingRulesRequest_Param.Marshal(b, m, deterministic)
}
func (m *ChangeAlertingRulesRequest_Param) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeAlertingRulesRequest_Param.Merge(m, src)
}
func (m *ChangeAlertingRulesRequest_Param) XXX_Size() int {
	return xxx_messageInfo_ChangeAlertingRulesRequest_Param.Size(m)
}
func (m *ChangeAlertingRulesRequest_Param) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeAlertingRulesRequest_Param.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeAlertingRulesRequest_Param proto.InternalMessageInfo

func (m *ChangeAlertingRulesRequest_Param) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChangeAlertingRulesRequest_Param) GetValue() float32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *ChangeAlertingRulesRequest_Param) GetRemoveValue() bool {
	if m != nil {
		return m.RemoveValue
	}
	return false
}

type ChangeAlertingRulesResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeAlertingRulesResponse) Reset()         { *m = ChangeAlertingRulesResponse{} }
func (m *ChangeAlertingRulesResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeAlertingRulesResponse) ProtoMessage()    {}
func (*ChangeAlertingRulesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f77c2da78f7912f5, []int{3}
}

func (m *ChangeAlertingRulesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeAlertingRulesResponse.Unmarshal(m, b)
}
func (m *ChangeAlertingRulesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeAlertingRulesResponse.Marshal(b, m, deterministic)
}
func (m *ChangeAlertingRulesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeAlertingRulesResponse.Merge(m, src)
}
func (m *ChangeAlertingRulesResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeAlertingRulesResponse.Size(m)
}
func (m *ChangeAlertingRulesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeAlertingRulesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeAlertingRulesResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("ia.v1beta1.ParamUnit", ParamUnit_name, ParamUnit_value)
	proto.RegisterEnum("ia.v1beta1.ParamType", ParamType_name, ParamType_value)
	proto.RegisterType((*ListAlertingRulesRequest)(nil), "ia.v1beta1.ListAlertingRulesRequest")
	proto.RegisterType((*ListAlertingRulesResponse)(nil), "ia.v1beta1.ListAlertingRulesResponse")
	proto.RegisterType((*ListAlertingRulesResponse_Param)(nil), "ia.v1beta1.ListAlertingRulesResponse.Param")
	proto.RegisterType((*ListAlertingRulesResponse_Rule)(nil), "ia.v1beta1.ListAlertingRulesResponse.Rule")
	proto.RegisterType((*ChangeAlertingRulesRequest)(nil), "ia.v1beta1.ChangeAlertingRulesRequest")
	proto.RegisterType((*ChangeAlertingRulesRequest_Param)(nil), "ia.v1beta1.ChangeAlertingRulesRequest.Param")
	proto.RegisterType((*ChangeAlertingRulesResponse)(nil), "ia.v1beta1.ChangeAlertingRulesResponse")
}

func init() {
	proto.RegisterFile("managementpb/ia/rules.proto", fileDescriptor_f77c2da78f7912f5)
}

var fileDescriptor_f77c2da78f7912f5 = []byte{
	// 712 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x4e, 0x13, 0x4d,
	0x18, 0xfe, 0xb6, 0x7f, 0xb4, 0x6f, 0xf9, 0x08, 0xdf, 0x7c, 0x4a, 0x96, 0xe5, 0xc7, 0x52, 0x54,
	0x4a, 0x91, 0xdd, 0x50, 0x12, 0x0f, 0x38, 0xb2, 0x40, 0x31, 0x24, 0x88, 0xcd, 0xa6, 0x10, 0x35,
	0x26, 0x64, 0x6a, 0x87, 0x32, 0x71, 0x77, 0x66, 0xdd, 0xce, 0x16, 0x38, 0xf5, 0xcc, 0x43, 0xe3,
	0x45, 0x78, 0x1f, 0xde, 0x02, 0x17, 0x60, 0x62, 0xbc, 0x06, 0x0f, 0x3c, 0x32, 0x3b, 0x33, 0x2d,
	0x8d, 0xb6, 0xb6, 0x67, 0xf3, 0xce, 0xfb, 0x3c, 0xf3, 0xce, 0xf3, 0xcc, 0xb3, 0x0b, 0x0b, 0x3e,
	0x66, 0xb8, 0x4d, 0x7c, 0xc2, 0x44, 0xd0, 0x74, 0x28, 0x76, 0xc2, 0xc8, 0x23, 0x1d, 0x3b, 0x08,
	0xb9, 0xe0, 0x08, 0x28, 0xb6, 0xbb, 0x5b, 0x4d, 0x22, 0xf0, 0x96, 0xf5, 0xb8, 0x4d, 0xc5, 0x45,
	0xd4, 0xb4, 0xdf, 0x70, 0xdf, 0xf1, 0x2f, 0xa9, 0x78, 0xcb, 0x2f, 0x9d, 0x36, 0xdf, 0x94, 0xc0,
	0xcd, 0x2e, 0xf6, 0x68, 0x0b, 0x0b, 0x1e, 0x76, 0x9c, 0xfe, 0x52, 0x9d, 0x61, 0x2d, 0xb6, 0x39,
	0x6f, 0x7b, 0xc4, 0xc1, 0x01, 0x75, 0x30, 0x63, 0x5c, 0x60, 0x41, 0x39, 0xd3, 0x13, 0xac, 0x65,
	0xdd, 0x95, 0x55, 0x33, 0x3a, 0x77, 0x5a, 0x51, 0x28, 0x01, 0xaa, 0x5f, 0xac, 0x80, 0x79, 0x44,
	0x3b, 0xa2, 0xea, 0x91, 0x50, 0x50, 0xd6, 0x76, 0xe3, 0xcb, 0xb9, 0xe4, 0x5d, 0x44, 0x3a, 0x02,
	0xcd, 0x41, 0x26, 0x24, 0x1e, 0xc7, 0x2d, 0xd3, 0x28, 0x18, 0xa5, 0xac, 0xab, 0xab, 0xe2, 0x4d,
	0x0a, 0xe6, 0x87, 0x90, 0x3a, 0x01, 0x67, 0x1d, 0x82, 0x9e, 0x40, 0x5a, 0x4a, 0x34, 0x8d, 0x42,
	0xb2, 0x94, 0xaf, 0x94, 0xed, 0x5b, 0x8d, 0xf6, 0x48, 0x96, 0x1d, 0x57, 0xae, 0x22, 0x5a, 0x3f,
	0x0d, 0x48, 0xd7, 0x71, 0x88, 0x7d, 0x84, 0x20, 0xc5, 0xb0, 0x4f, 0xe4, 0xfc, 0x9c, 0x2b, 0xd7,
	0xf1, 0xde, 0x05, 0xf1, 0x02, 0x33, 0xa1, 0xf6, 0xe2, 0x35, 0x5a, 0x87, 0x54, 0xc4, 0xa8, 0x30,
	0x93, 0x05, 0xa3, 0x34, 0x53, 0xb9, 0x3b, 0x38, 0x52, 0x1e, 0x74, 0xc2, 0xa8, 0x70, 0x25, 0x24,
	0x86, 0x8a, 0xeb, 0x80, 0x98, 0xa9, 0x11, 0xd0, 0xc6, 0x75, 0x40, 0x5c, 0x09, 0x41, 0x0b, 0x90,
	0xf3, 0x29, 0x3b, 0xeb, 0x62, 0x2f, 0x22, 0x66, 0xba, 0x60, 0x94, 0x12, 0x6e, 0xd6, 0xa7, 0xec,
	0x34, 0xae, 0x65, 0x13, 0x5f, 0xe9, 0x66, 0x46, 0x37, 0xf1, 0x95, 0x6a, 0xae, 0xc2, 0xbf, 0x2d,
	0x72, 0x8e, 0x23, 0x4f, 0x68, 0xc0, 0x94, 0x04, 0x4c, 0xeb, 0x4d, 0x05, 0xba, 0x03, 0x69, 0xd5,
	0xcc, 0xca, 0xa6, 0x2a, 0xac, 0x1f, 0x06, 0xa4, 0x62, 0x33, 0x86, 0x6a, 0x37, 0x61, 0x8a, 0x30,
	0xdc, 0xf4, 0x48, 0x4b, 0xca, 0xcf, 0xba, 0xbd, 0xb2, 0xef, 0x4a, 0x72, 0xc0, 0x95, 0x3d, 0xc8,
	0x04, 0xb1, 0xa4, 0x8e, 0x99, 0x92, 0x4f, 0xb1, 0x31, 0xd9, 0x53, 0x48, 0x1b, 0x5c, 0x4d, 0x45,
	0x3b, 0x90, 0xef, 0x49, 0x39, 0xe7, 0xa1, 0xb4, 0x21, 0x5f, 0x99, 0xb7, 0x55, 0xac, 0xec, 0x5e,
	0xac, 0xec, 0x7d, 0x1d, 0x2b, 0x17, 0x34, 0xfa, 0x80, 0x87, 0x68, 0x03, 0x92, 0x31, 0x27, 0x33,
	0x8e, 0x13, 0xa3, 0x8a, 0x5f, 0x12, 0x60, 0xed, 0x5d, 0x60, 0xd6, 0x26, 0x43, 0xc3, 0x68, 0x0d,
	0xda, 0xb1, 0x9b, 0xf9, 0xf6, 0xf5, 0x5e, 0xe2, 0x85, 0x31, 0xd6, 0x96, 0xfd, 0xbe, 0x05, 0x49,
	0x69, 0xc1, 0xa3, 0x41, 0x0b, 0x46, 0x4f, 0xfb, 0xcd, 0x03, 0xad, 0x23, 0x35, 0x89, 0x0e, 0xb4,
	0x04, 0x10, 0x12, 0x9f, 0x77, 0x49, 0xdf, 0xaf, 0xac, 0x9b, 0x53, 0x3b, 0x07, 0x3c, 0xb4, 0x5e,
	0xf7, 0xb2, 0xfd, 0x37, 0x41, 0xfd, 0x68, 0x24, 0x06, 0xa2, 0x81, 0x56, 0x60, 0x5a, 0x9f, 0xac,
	0x9a, 0x49, 0x79, 0x76, 0x5e, 0xed, 0xc9, 0x4c, 0x15, 0x97, 0x60, 0x61, 0xa8, 0x2a, 0xf5, 0xb4,
	0xe5, 0x6d, 0xc8, 0xf5, 0xbf, 0x07, 0x34, 0x07, 0xa8, 0x5e, 0x75, 0xab, 0xcf, 0xce, 0x4e, 0x8e,
	0x0f, 0x1b, 0x67, 0x87, 0xc7, 0xa7, 0xd5, 0xa3, 0xc3, 0xfd, 0xd9, 0x7f, 0xd0, 0x0c, 0x40, 0xbd,
	0xe6, 0xee, 0xd5, 0x8e, 0x1b, 0xd5, 0xa7, 0xb5, 0x59, 0xa3, 0x6c, 0x6b, 0x52, 0xfc, 0x65, 0xdc,
	0x92, 0x1a, 0x2f, 0xeb, 0xb5, 0x01, 0x52, 0x0e, 0xd2, 0x07, 0x47, 0xcf, 0xab, 0x8d, 0x59, 0xa3,
	0xf2, 0x39, 0x01, 0x69, 0x39, 0x16, 0x7d, 0x30, 0xe0, 0xbf, 0x3f, 0x72, 0x86, 0xee, 0x8f, 0x89,
	0xa1, 0x7c, 0x01, 0xeb, 0xc1, 0x44, 0x61, 0x2d, 0xae, 0xbd, 0xbf, 0xf9, 0xfe, 0x29, 0xb1, 0x52,
	0x5c, 0x74, 0xba, 0x5b, 0xce, 0xed, 0xaf, 0x36, 0xfe, 0xd1, 0x4a, 0xa0, 0x13, 0x53, 0x77, 0x8c,
	0x32, 0xfa, 0x68, 0xc0, 0xff, 0x43, 0xac, 0x41, 0x0f, 0x27, 0x4b, 0x84, 0xb5, 0x36, 0x16, 0xa7,
	0x6f, 0xb4, 0x2e, 0x6f, 0xb4, 0x5a, 0x5c, 0x1e, 0x75, 0x23, 0x45, 0xde, 0x31, 0xca, 0xbb, 0xf9,
	0x57, 0x39, 0x8a, 0xf5, 0x99, 0xcd, 0x8c, 0xcc, 0xd3, 0xf6, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xa1, 0x52, 0x56, 0x46, 0x31, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RulesClient is the client API for Rules service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RulesClient interface {
	// ListAlertingRules returns a list of all Integrated Alerting rules.
	ListAlertingRules(ctx context.Context, in *ListAlertingRulesRequest, opts ...grpc.CallOption) (*ListAlertingRulesResponse, error)
	// ChangeAlertingRules changes Integrated Alerting rule.
	ChangeAlertingRules(ctx context.Context, in *ChangeAlertingRulesRequest, opts ...grpc.CallOption) (*ChangeAlertingRulesResponse, error)
}

type rulesClient struct {
	cc grpc.ClientConnInterface
}

func NewRulesClient(cc grpc.ClientConnInterface) RulesClient {
	return &rulesClient{cc}
}

func (c *rulesClient) ListAlertingRules(ctx context.Context, in *ListAlertingRulesRequest, opts ...grpc.CallOption) (*ListAlertingRulesResponse, error) {
	out := new(ListAlertingRulesResponse)
	err := c.cc.Invoke(ctx, "/ia.v1beta1.Rules/ListAlertingRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rulesClient) ChangeAlertingRules(ctx context.Context, in *ChangeAlertingRulesRequest, opts ...grpc.CallOption) (*ChangeAlertingRulesResponse, error) {
	out := new(ChangeAlertingRulesResponse)
	err := c.cc.Invoke(ctx, "/ia.v1beta1.Rules/ChangeAlertingRules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RulesServer is the server API for Rules service.
type RulesServer interface {
	// ListAlertingRules returns a list of all Integrated Alerting rules.
	ListAlertingRules(context.Context, *ListAlertingRulesRequest) (*ListAlertingRulesResponse, error)
	// ChangeAlertingRules changes Integrated Alerting rule.
	ChangeAlertingRules(context.Context, *ChangeAlertingRulesRequest) (*ChangeAlertingRulesResponse, error)
}

// UnimplementedRulesServer can be embedded to have forward compatible implementations.
type UnimplementedRulesServer struct {
}

func (*UnimplementedRulesServer) ListAlertingRules(ctx context.Context, req *ListAlertingRulesRequest) (*ListAlertingRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAlertingRules not implemented")
}
func (*UnimplementedRulesServer) ChangeAlertingRules(ctx context.Context, req *ChangeAlertingRulesRequest) (*ChangeAlertingRulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeAlertingRules not implemented")
}

func RegisterRulesServer(s *grpc.Server, srv RulesServer) {
	s.RegisterService(&_Rules_serviceDesc, srv)
}

func _Rules_ListAlertingRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlertingRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RulesServer).ListAlertingRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ia.v1beta1.Rules/ListAlertingRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RulesServer).ListAlertingRules(ctx, req.(*ListAlertingRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rules_ChangeAlertingRules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeAlertingRulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RulesServer).ChangeAlertingRules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ia.v1beta1.Rules/ChangeAlertingRules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RulesServer).ChangeAlertingRules(ctx, req.(*ChangeAlertingRulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Rules_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ia.v1beta1.Rules",
	HandlerType: (*RulesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAlertingRules",
			Handler:    _Rules_ListAlertingRules_Handler,
		},
		{
			MethodName: "ChangeAlertingRules",
			Handler:    _Rules_ChangeAlertingRules_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "managementpb/ia/rules.proto",
}
