// Code generated by go-swagger; DO NOT EDIT.

package rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewChangeAlertingRulesParams creates a new ChangeAlertingRulesParams object
// with the default values initialized.
func NewChangeAlertingRulesParams() *ChangeAlertingRulesParams {
	var ()
	return &ChangeAlertingRulesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewChangeAlertingRulesParamsWithTimeout creates a new ChangeAlertingRulesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewChangeAlertingRulesParamsWithTimeout(timeout time.Duration) *ChangeAlertingRulesParams {
	var ()
	return &ChangeAlertingRulesParams{

		timeout: timeout,
	}
}

// NewChangeAlertingRulesParamsWithContext creates a new ChangeAlertingRulesParams object
// with the default values initialized, and the ability to set a context for a request
func NewChangeAlertingRulesParamsWithContext(ctx context.Context) *ChangeAlertingRulesParams {
	var ()
	return &ChangeAlertingRulesParams{

		Context: ctx,
	}
}

// NewChangeAlertingRulesParamsWithHTTPClient creates a new ChangeAlertingRulesParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewChangeAlertingRulesParamsWithHTTPClient(client *http.Client) *ChangeAlertingRulesParams {
	var ()
	return &ChangeAlertingRulesParams{
		HTTPClient: client,
	}
}

/*ChangeAlertingRulesParams contains all the parameters to send to the API endpoint
for the change alerting rules operation typically these are written to a http.Request
*/
type ChangeAlertingRulesParams struct {

	/*Body*/
	Body ChangeAlertingRulesBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the change alerting rules params
func (o *ChangeAlertingRulesParams) WithTimeout(timeout time.Duration) *ChangeAlertingRulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the change alerting rules params
func (o *ChangeAlertingRulesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the change alerting rules params
func (o *ChangeAlertingRulesParams) WithContext(ctx context.Context) *ChangeAlertingRulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the change alerting rules params
func (o *ChangeAlertingRulesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the change alerting rules params
func (o *ChangeAlertingRulesParams) WithHTTPClient(client *http.Client) *ChangeAlertingRulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the change alerting rules params
func (o *ChangeAlertingRulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the change alerting rules params
func (o *ChangeAlertingRulesParams) WithBody(body ChangeAlertingRulesBody) *ChangeAlertingRulesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the change alerting rules params
func (o *ChangeAlertingRulesParams) SetBody(body ChangeAlertingRulesBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ChangeAlertingRulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
