// Code generated by go-swagger; DO NOT EDIT.

package rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChangeAlertingRulesReader is a Reader for the ChangeAlertingRules structure.
type ChangeAlertingRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ChangeAlertingRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewChangeAlertingRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewChangeAlertingRulesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewChangeAlertingRulesOK creates a ChangeAlertingRulesOK with default headers values
func NewChangeAlertingRulesOK() *ChangeAlertingRulesOK {
	return &ChangeAlertingRulesOK{}
}

/*ChangeAlertingRulesOK handles this case with default header values.

A successful response.
*/
type ChangeAlertingRulesOK struct {
	Payload interface{}
}

func (o *ChangeAlertingRulesOK) Error() string {
	return fmt.Sprintf("[POST /v1/management/ia/Rules/Change][%d] changeAlertingRulesOk  %+v", 200, o.Payload)
}

func (o *ChangeAlertingRulesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *ChangeAlertingRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewChangeAlertingRulesDefault creates a ChangeAlertingRulesDefault with default headers values
func NewChangeAlertingRulesDefault(code int) *ChangeAlertingRulesDefault {
	return &ChangeAlertingRulesDefault{
		_statusCode: code,
	}
}

/*ChangeAlertingRulesDefault handles this case with default header values.

An unexpected error response
*/
type ChangeAlertingRulesDefault struct {
	_statusCode int

	Payload *ChangeAlertingRulesDefaultBody
}

// Code gets the status code for the change alerting rules default response
func (o *ChangeAlertingRulesDefault) Code() int {
	return o._statusCode
}

func (o *ChangeAlertingRulesDefault) Error() string {
	return fmt.Sprintf("[POST /v1/management/ia/Rules/Change][%d] ChangeAlertingRules default  %+v", o._statusCode, o.Payload)
}

func (o *ChangeAlertingRulesDefault) GetPayload() *ChangeAlertingRulesDefaultBody {
	return o.Payload
}

func (o *ChangeAlertingRulesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ChangeAlertingRulesDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*ChangeAlertingRulesBody change alerting rules body
swagger:model ChangeAlertingRulesBody
*/
type ChangeAlertingRulesBody struct {

	// Rule name.
	Name string `json:"name,omitempty"`

	// Sets new rule status: enabled or disabled. Must always be sent.
	Enabled bool `json:"enabled,omitempty"`

	// Parameters to change. Missing parameters will not be changed.
	Params []*ParamsItems0 `json:"params"`

	// Rule set duration.
	For string `json:"for,omitempty"`

	// Remove set duration (reset to default).
	RemoveFor bool `json:"remove_for,omitempty"`
}

// Validate validates this change alerting rules body
func (o *ChangeAlertingRulesBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateParams(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ChangeAlertingRulesBody) validateParams(formats strfmt.Registry) error {

	if swag.IsZero(o.Params) { // not required
		return nil
	}

	for i := 0; i < len(o.Params); i++ {
		if swag.IsZero(o.Params[i]) { // not required
			continue
		}

		if o.Params[i] != nil {
			if err := o.Params[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("body" + "." + "params" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ChangeAlertingRulesBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ChangeAlertingRulesBody) UnmarshalBinary(b []byte) error {
	var res ChangeAlertingRulesBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*ChangeAlertingRulesDefaultBody change alerting rules default body
swagger:model ChangeAlertingRulesDefaultBody
*/
type ChangeAlertingRulesDefaultBody struct {

	// error
	Error string `json:"error,omitempty"`

	// code
	Code int32 `json:"code,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// details
	Details []*DetailsItems0 `json:"details"`
}

// Validate validates this change alerting rules default body
func (o *ChangeAlertingRulesDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ChangeAlertingRulesDefaultBody) validateDetails(formats strfmt.Registry) error {

	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ChangeAlertingRules default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ChangeAlertingRulesDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ChangeAlertingRulesDefaultBody) UnmarshalBinary(b []byte) error {
	var res ChangeAlertingRulesDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DetailsItems0 details items0
swagger:model DetailsItems0
*/
type DetailsItems0 struct {

	// type url
	TypeURL string `json:"type_url,omitempty"`

	// value
	// Format: byte
	Value strfmt.Base64 `json:"value,omitempty"`
}

// Validate validates this details items0
func (o *DetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DetailsItems0) UnmarshalBinary(b []byte) error {
	var res DetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*ParamsItems0 Param repsesents a single Integrated Alerting rule parameter change.
swagger:model ParamsItems0
*/
type ParamsItems0 struct {

	// Parameter name.
	Name string `json:"name,omitempty"`

	// Parameter set value (float).
	Value float32 `json:"value,omitempty"`

	// Remove set value (reset to default).
	RemoveValue bool `json:"remove_value,omitempty"`
}

// Validate validates this params items0
func (o *ParamsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *ParamsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ParamsItems0) UnmarshalBinary(b []byte) error {
	var res ParamsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
