// Code generated by go-swagger; DO NOT EDIT.

package rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ListAlertingRulesReader is a Reader for the ListAlertingRules structure.
type ListAlertingRulesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListAlertingRulesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListAlertingRulesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListAlertingRulesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListAlertingRulesOK creates a ListAlertingRulesOK with default headers values
func NewListAlertingRulesOK() *ListAlertingRulesOK {
	return &ListAlertingRulesOK{}
}

/*ListAlertingRulesOK handles this case with default header values.

A successful response.
*/
type ListAlertingRulesOK struct {
	Payload interface{}
}

func (o *ListAlertingRulesOK) Error() string {
	return fmt.Sprintf("[POST /v1/management/ia/Rules/List][%d] listAlertingRulesOk  %+v", 200, o.Payload)
}

func (o *ListAlertingRulesOK) GetPayload() interface{} {
	return o.Payload
}

func (o *ListAlertingRulesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListAlertingRulesDefault creates a ListAlertingRulesDefault with default headers values
func NewListAlertingRulesDefault(code int) *ListAlertingRulesDefault {
	return &ListAlertingRulesDefault{
		_statusCode: code,
	}
}

/*ListAlertingRulesDefault handles this case with default header values.

An unexpected error response
*/
type ListAlertingRulesDefault struct {
	_statusCode int

	Payload *ListAlertingRulesDefaultBody
}

// Code gets the status code for the list alerting rules default response
func (o *ListAlertingRulesDefault) Code() int {
	return o._statusCode
}

func (o *ListAlertingRulesDefault) Error() string {
	return fmt.Sprintf("[POST /v1/management/ia/Rules/List][%d] ListAlertingRules default  %+v", o._statusCode, o.Payload)
}

func (o *ListAlertingRulesDefault) GetPayload() *ListAlertingRulesDefaultBody {
	return o.Payload
}

func (o *ListAlertingRulesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(ListAlertingRulesDefaultBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DetailsItems0 details items0
swagger:model DetailsItems0
*/
type DetailsItems0 struct {

	// type url
	TypeURL string `json:"type_url,omitempty"`

	// value
	// Format: byte
	Value strfmt.Base64 `json:"value,omitempty"`
}

// Validate validates this details items0
func (o *DetailsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *DetailsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DetailsItems0) UnmarshalBinary(b []byte) error {
	var res DetailsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*ListAlertingRulesDefaultBody list alerting rules default body
swagger:model ListAlertingRulesDefaultBody
*/
type ListAlertingRulesDefaultBody struct {

	// error
	Error string `json:"error,omitempty"`

	// code
	Code int32 `json:"code,omitempty"`

	// message
	Message string `json:"message,omitempty"`

	// details
	Details []*DetailsItems0 `json:"details"`
}

// Validate validates this list alerting rules default body
func (o *ListAlertingRulesDefaultBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *ListAlertingRulesDefaultBody) validateDetails(formats strfmt.Registry) error {

	if swag.IsZero(o.Details) { // not required
		return nil
	}

	for i := 0; i < len(o.Details); i++ {
		if swag.IsZero(o.Details[i]) { // not required
			continue
		}

		if o.Details[i] != nil {
			if err := o.Details[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("ListAlertingRules default" + "." + "details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *ListAlertingRulesDefaultBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *ListAlertingRulesDefaultBody) UnmarshalBinary(b []byte) error {
	var res ListAlertingRulesDefaultBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
